### PR TITLE
Convert the vagabundo-frontend CI pipeline to GitHub Workflow

### PR DESCRIPTION
**Pull request by olof-nord**
This PR takes the existing Jenkins-Based vagabundo-frontend CI pipeline and converts it without changes to a GitHub Workflow-compatible pipeline.

It additionally moves the .editorconfig file to the root of the repo as to start reap the benefits of a monorepo structure.

### CODE REVIEW

**Comment by ionicsolutions** [comment]
Thanks 👍 Is there a need to have backend and frontend tests and deployment in the same workflow file?

**Comment by olof-nord** [comment]
> Thanks +1 Is there a need to have backend and frontend tests and deployment in the same workflow file?

Definitely. Saves potential merge conflicts and splits up the content nice and clean. Let me know what you think about the naming - for now I am focusing just on the frontend as to keep this PR small

**Comment by olof-nord** [comment]
Actually executing the build & test makes it clear that there is definitely more work needed than just migrating the Jenkinsfiles, as with the Jenkinsfile we used the `withCredentials` plugin for the AWS credentials. I say we merge this one, and then we could work getting the AWS credentials in place again with GitHub separately.

**Comment by ionicsolutions** [comment]
Integrating with AWS is pretty straightforward, they have their own collection of Actions to re-use: [aws-actions](https://github.com/aws-actions). I set it up for the CloudFormation staging deployment already: [.github/workflows/staging.yml](https://github.com/senacor/vagabundo/blob/cloudformation-refactoring/.github/workflows/staging.yml)

I guess what we need here is something like this third-party [S3 File Upload](https://github.com/marketplace/actions/s3-file-upload) action. The credentials I configured as Secrets should allow for S3 uploads, as this is required for the Lambdas as well.

(My plan is to deploy all `master` pushes (either directly or through merging PRs) to a staging environment and to use the GitHub release feature to trigger production deployments.)

**Pull request closed without merging**
